### ISSUE TITLE
repckg-approach: ReadMe Instructions

### ISSUE THREAD

**Issue by AntonSchmied** [nonlinear-labs-dev/Audiophile2NonLinux#10]
A bit nitpicky, yes ... but:
In the ReadMe Instructions under _Install NonLinux_ -> _On a NUC Machine_

call ./createUSBStick**.sh** /path/to/NonLinux.iso /dev/sdX worked me. 
could not get it to run without the suffix.

**Comment by hhoegelo** [comment]
Of course ... not nitpicking at all ... fixed it
