### ISSUE TITLE
grub entries missing ?

### ISSUE THREAD

**Issue by majjam** [nonlinear-labs-dev/Audiophile2NonLinux#5]
repackaging approach - not booting

1. created iso within linux mint -> ok
2. installed iso on vm with unpartitioned disk  (no EFI aktivated) -> ok
3. booting -> grub without any entries
4. reboot iso from 1 on installed system -> hang at startup

**Comment by hhoegelo** [comment]
I think EFI has to be activated in order for the installation to work.

**Comment by majjam** [comment]
Thanks ,can be closed.
What happend : 
1st installs and boots only if EFI is activated (like you wrote)
2nd on earlier versions on failed preconditions check (e.g. pre-partitioned disks) installer stopped without a message and without the ability to delete the partitions, so i arrived in a dead end situation.
