### ISSUE TITLE
repckg-approach: unmount USB before deploying the image

### ISSUE THREAD

**Issue by AntonSchmied** [nonlinear-labs-dev/Audiophile2NonLinux#6]
The USB stick for the .iso has to be unmounted in order for _createUSBStick.sh_ to function correctly - maybe **umount** in the in the script just in case

**Comment by hhoegelo** [comment]
I tested it on my system and the script worked well, even though the target USB stick was mounted. Can you please provide more info, i.e. what exactly does not function correctly? Are there error messages?

**Comment by hhoegelo** [comment]
OK, forget it - I could just reproduce it.
