### ISSUE TITLE
repckg-approach: clean SSD before Installation from USB

### ISSUE THREAD

**Issue by AntonSchmied** [nonlinear-labs-dev/Audiophile2NonLinux#8]
In order for the Installation from USB Stick to function properly, the SSD must be empty/ cleared. Otherwise it will hang with a blinking underscore on the screen.

**Comment by hhoegelo** [comment]
I changed the script in a way that it will throw you into a shell to fix the partitioning problem. Once you leave the shell, it will try to install again.
Still, you have to answer the mkfs-questions regarding the already existing file systems with "y".
