### ISSUE TITLE
repckg-approach: USB Installation Automation

### ISSUE THREAD

**Issue by AntonSchmied** [nonlinear-labs-dev/Audiophile2NonLinux#9]
In order for the Installation from USB to run automatically, tweak BIOS to allow **Boot from USB first* instead of UEFI Shell. Otherwise the USB has to manually be chosen via UEFI Shell or in BIOS by choosing the bootable device [F10 on Intel in our case]

**Comment by hhoegelo** [comment]
I updated the documentation accordingly as there is nothing I could probably do in the scripts to solve the problem.
